from django.conf.urls import url

from .views import (portfolio_greeting_page,
                    portfolio_image_list,
                    portfolio_image_create,
                    portfolio_image_update,
                    portfolio_image_detail,
                    portfolio_image_delete,
                    portfolio_image_clear_views,
                    portfolio_category_list,
                    portfolio_category_create,
                    portfolio_category_update,
                    portfolio_category_detail,
                    portfolio_category_delete,
                    portfolio_slider_images_list,
                    portfolio_slider_images_create,
                    portfolio_slider_images_update,
                    portfolio_slider_images_delete,
                    about_me,
                    about_me_create,
                    about_me_update,
                    contact,
                    )


urlpatterns = [
    url(r'^$', portfolio_greeting_page, name='portfolio_greeting_page'),
    url(r'^portfolio/$', portfolio_image_list, name='portfolio_image_list'),
    url(r'^portfolio/by_category/(?P<category_slug>[-\w]+)/$', portfolio_image_list, name='portfolio_home_by_category'),
    url(r'^portfolio/create/$', portfolio_image_create, name='portfolio_image_create_form'),
    url(r'^portfolio/(?P<image_id>\d+)/(?P<image_slug>[-\w]+)/$', portfolio_image_detail, name='portfolio_image_detail'),
    url(r'^portfolio/(?P<image_id>\d+)/(?P<image_slug>[-\w]+)/edit/$', portfolio_image_update, name='portfolio_image_update'),
    url(r'^portfolio/(?P<image_id>\d+)/(?P<image_slug>[-\w]+)/clear/$', portfolio_image_clear_views, name='portfolio_image_clear_views'),
    url(r'^portfolio/(?P<image_id>\d+)/(?P<image_slug>[-\w]+)/delete/$', portfolio_image_delete, name='portfolio_image_delete'),
    url(r'^portfolio/category/$', portfolio_category_list, name='portfolio_category_list'),
    url(r'^portfolio/category/create/$', portfolio_category_create, name='portfolio_category_create'),
    url(r'^portfolio/category/(?P<category_conf_slug>[-\w]+)/$', portfolio_category_detail, name='portfolio_category_detail'),
    url(r'^portfolio/category/(?P<category_conf_slug>[-\w]+)/edit/$', portfolio_category_update, name='portfolio_category_update'),
    url(r'^portfolio/category/(?P<category_conf_slug>[-\w]+)/delete/$', portfolio_category_delete, name='portfolio_category_delete'),
    url(r'^portfolio/slider-images/$', portfolio_slider_images_list, name='portfolio_slider_images_list'),
    url(r'^portfolio/slider-images/create/$', portfolio_slider_images_create, name='portfolio_slider_images_create'),
    url(r'^portfolio/slider-images/(?P<slider_id>[-\w]+)/edit/$', portfolio_slider_images_update, name='portfolio_slider_images_update'),
    url(r'^portfolio/slider-images/(?P<slider_id>[-\w]+)/delete/$', portfolio_slider_images_delete, name='portfolio_slider_images_delete'),
    url(r'^portfolio/about-me/$', about_me, name='about_me'),
    url(r'^portfolio/about-me/create/$', about_me_create, name='about_me_create'),
    url(r'^portfolio/about_me/(?P<about_me_id>[-\w]+)/edit/$', about_me_update, name='about_me_update'),
    url(r'^portfolio/contact_form/$', contact, name='contact_form'),
]
